export const companyTitle = [
  "CEO",
  "Founder",
  "Co-founder",
  "Director",
  "President",
  "Chief Operating Officer (COO)",
  "Chief Financial Officer (CFO)",
  "Chief Technology Officer (CTO)",
  "Chief Marketing Officer (CMO)",
  "Chief Revenue Officer (CRO)",
  "Chief Strategy Officer (CSO)",
  "Chief Information Officer (CIO)",
  "Chief Human Resources Officer (CHRO)",
  "Chief Legal Officer (CLO)",
  "Executive Vice President",
  "Senior Vice President",
  "Vice President of Sales",
  "Vice President of Operations",
  "Vice President of Engineering",
  "Vice President of Finance",
  "Vice President of Marketing",
  "Vice President of Business Development",
  "Vice President of Product Management",
  "Vice President of Customer Success",
  "Vice President of Supply Chain",
  "General Manager",
  "Head of Innovation",
  "Head of Corporate Development",
  "Head of Research and Development (R&D)",
  "Head of Legal Affairs",
  "Head of Compliance",
  "Head of Diversity and Inclusion",
  "Head of Environmental Sustainability",
  "Director of Sales Operations",
  "Director of Customer Experience",
  "Director of Information Technology (IT)",
  "Director of Public Relations (PR)",
  "Director of Quality Assurance (QA)",
  "Director of Supply Chain Management",
  "Director of Corporate Social Responsibility (CSR)",
  "Director of Talent Acquisition",
  "Director of Learning and Development",
  "Director of Strategic Partnerships",
  "Director of Brand Management",
  "Director of Risk Management",
  "Director of Product Development",
  "Director of Corporate Finance",
  "Director of Investor Relations",
  "Director of Regulatory Affairs",
  "Director of Business Intelligence",
  "Director of Facilities Management",
  "Director of Project Management Office (PMO)",
  "Director of Corporate Strategy",
  "Manager of Sales Operations",
  "Manager of Customer Success",
  "Manager of Information Security",
  "Manager of Corporate Events",
  "Manager of Employee Relations",
  "Manager of Procurement",
  "Manager of Marketing Analytics",
  "Manager of Internal Audit",
  "Manager of Market Research",
  "Manager of Sustainability Programs",
  "Supervisor of Production Planning",
  "Supervisor of Technical Support",
  "Supervisor of Accounts Payable",
  "Supervisor of Facilities Maintenance",
  "Supervisor of Inventory Control",
  "Supervisor of Customer Service",
  "Supervisor of Regulatory Compliance",
  "Supervisor of Quality Control",
  "Supervisor of Training and Development",
  "Supervisor of Vendor Management",
  "Team Lead of Software Development",
  "Team Lead of Digital Marketing",
  "Team Lead of Content Creation",
  "Team Lead of Business Analysis",
  "Team Lead of Customer Relations",
  "Team Lead of Sales Enablement",
  "Team Lead of Product Design",
  "Team Lead of Data Analytics",
  "Team Lead of Operations Planning",
  "Team Lead of Research Coordination",
  "Coordinator of Corporate Events",
  "Coordinator of Community Engagement",
  "Coordinator of Employee Benefits",
  "Coordinator of Workplace Safety",
  "Coordinator of Internal Communications",
  "Coordinator of Regulatory Filings",
  "Coordinator of Procurement Logistics",
  "Coordinator of Marketing Campaigns",
  "Coordinator of Training Programs",
  "Coordinator of Sustainability Initiatives",
];
